export interface VideoData {
  id: number;
  upload_date: string;
  tag: string;
  p1_name: string;
  p1_char: string;
  p2_name: string;
  p2_char: string;
  video_link: string;
  game: string;
}

// Sample of first 50 videos from the JSON data
export const VIDEOS: VideoData[] = [
  {
    id: 426457,
    upload_date: '2025-12-22',
    tag: 'Fightcade FT5',
    p1_name: 'number1gouki',
    p1_char: 'Akuma',
    p2_name: 'Onagai',
    p2_char: 'Ken',
    video_link: 'https://www.youtube.com/watch?v=td88v_IDftc',
    game: 'Street Fighter III: 3rd Strike',
  },
  {
    id: 425384,
    upload_date: '2025-12-21',
    tag: 'Fightcade FT5',
    p1_name: 'Nazca',
    p1_char: 'Akuma',
    p2_name: 'SuperHyperBomb',
    p2_char: 'Alex',
    video_link: 'https://www.youtube.com/watch?v=qIHqNJ1nIoI',
    game: 'Street Fighter III: 3rd Strike',
  },
  {
    id: 425259,
    upload_date: '2025-12-20',
    tag: 'Fightcade FT3',
    p1_name: 'Inthul',
    p1_char: 'Q',
    p2_name: 'Buu HaHa',
    p2_char: 'Twelve',
    video_link: 'https://www.youtube.com/watch?v=_xDrTjzWjo8',
    game: 'Street Fighter III: 3rd Strike',
  },
  {
    id: 425082,
    upload_date: '2025-12-19',
    tag: 'Fightcade FT5',
    p1_name: 'Virsaga',
    p1_char: 'Ken',
    p2_name: 'Cruise',
    p2_char: 'Urien',
    video_link: 'https://www.youtube.com/watch?v=Lgjj5aT0pBs',
    game: 'Street Fighter III: 3rd Strike',
  },
  {
    id: 424864,
    upload_date: '2025-12-17',
    tag: 'Fightcade FT3',
    p1_name: 'JEWELBOX',
    p1_char: 'Elena',
    p2_name: 'AlorsFaim',
    p2_char: 'Yun',
    video_link: 'https://www.youtube.com/watch?v=JlxgImIxfPA',
    game: 'Street Fighter III: 3rd Strike',
  },
  {
    id: 424753,
    upload_date: '2025-12-16',
    tag: 'Fightcade FT5',
    p1_name: 'n_cruz',
    p1_char: 'Urien',
    p2_name: 'orogasm',
    p2_char: 'Oro',
    video_link: 'https://www.youtube.com/watch?v=clbhG5qM7w4',
    game: 'Street Fighter III: 3rd Strike',
  },
  {
    id: 424637,
    upload_date: '2025-12-15',
    tag: 'Fightcade FT5',
    p1_name: 'yogurt brain',
    p1_char: 'Ibuki',
    p2_name: 'akaata1',
    p2_char: 'Yang',
    video_link: 'https://www.youtube.com/watch?v=Z7OMNH5AtZQ',
    game: 'Street Fighter III: 3rd Strike',
  },
  {
    id: 424237,
    upload_date: '2025-12-13',
    tag: 'Fightcade FT5',
    p1_name: 'MrPomegranX',
    p1_char: 'Akuma',
    p2_name: 'Inthul',
    p2_char: 'Q',
    video_link: 'https://www.youtube.com/watch?v=G6sJDX9PMSE',
    game: 'Street Fighter III: 3rd Strike',
  },
  {
    id: 424129,
    upload_date: '2025-12-12',
    tag: 'Fightcade FT5',
    p1_name: 'TenRUN',
    p1_char: 'Ibuki',
    p2_name: 'DrPancakeMd',
    p2_char: 'Makoto',
    video_link: 'https://www.youtube.com/watch?v=QNUaAlzFfVc',
    game: 'Street Fighter III: 3rd Strike',
  },
  {
    id: 424024,
    upload_date: '2025-12-11',
    tag: 'Fightcade FT5',
    p1_name: 'the.daolicious',
    p1_char: 'Yun',
    p2_name: 'AQH',
    p2_char: 'Necro',
    video_link: 'https://www.youtube.com/watch?v=8KEv_cwNrYs',
    game: 'Street Fighter III: 3rd Strike',
  },
  {
    id: 423792,
    upload_date: '2025-12-10',
    tag: 'Fightcade FT3',
    p1_name: 'Buu HaHa',
    p1_char: 'Twelve',
    p2_name: 'Wolveyes',
    p2_char: 'Ryu',
    video_link: 'https://www.youtube.com/watch?v=ozrRwjZ3mTM',
    game: 'Street Fighter III: 3rd Strike',
  },
  {
    id: 423679,
    upload_date: '2025-12-09',
    tag: 'Fightcade FT5',
    p1_name: 'Virsaga',
    p1_char: 'Ryu',
    p2_name: 'Duralath',
    p2_char: 'Alex',
    video_link: 'https://www.youtube.com/watch?v=D3THR3Gtgs0',
    game: 'Street Fighter III: 3rd Strike',
  },
  {
    id: 423456,
    upload_date: '2025-12-08',
    tag: 'Fightcade FT5',
    p1_name: '12oser',
    p1_char: 'Dudley',
    p2_name: 'LukeATX',
    p2_char: 'Akuma',
    video_link: 'https://www.youtube.com/watch?v=KQtfidnfHlw',
    game: 'Street Fighter III: 3rd Strike',
  },
  {
    id: 423325,
    upload_date: '2025-12-07',
    tag: 'Fightcade FT5',
    p1_name: 'yogurt brain',
    p1_char: 'Ibuki',
    p2_name: 'Cruise',
    p2_char: 'Urien',
    video_link: 'https://www.youtube.com/watch?v=ANG_dWQ260k',
    game: 'Street Fighter III: 3rd Strike',
  },
  {
    id: 423157,
    upload_date: '2025-12-06',
    tag: 'Fightcade FT5',
    p1_name: 'KUSOHAMUchan',
    p1_char: 'Urien',
    p2_name: 'SuperHyperBomb',
    p2_char: 'Alex',
    video_link: 'https://www.youtube.com/watch?v=8H871lJCMJY',
    game: 'Street Fighter III: 3rd Strike',
  },
  {
    id: 422839,
    upload_date: '2025-12-05',
    tag: 'Fightcade FT5',
    p1_name: 'jinjin2010',
    p1_char: 'Yun',
    p2_name: 'sean_tsukaimasu',
    p2_char: 'Sean',
    video_link: 'https://www.youtube.com/watch?v=23HkPWrsuuA',
    game: 'Street Fighter III: 3rd Strike',
  },
  {
    id: 422659,
    upload_date: '2025-12-04',
    tag: 'Fightcade FT3',
    p1_name: 'Alexander Newhati',
    p1_char: 'Hugo',
    p2_name: 'Crazierstairs',
    p2_char: 'Oro',
    video_link: 'https://www.youtube.com/watch?v=NPUGSfuLpdI',
    game: 'Street Fighter III: 3rd Strike',
  },
  {
    id: 422303,
    upload_date: '2025-12-03',
    tag: 'Fightcade FT5',
    p1_name: '12oser',
    p1_char: 'Dudley',
    p2_name: 'Dagger_G',
    p2_char: 'Remy',
    video_link: 'https://www.youtube.com/watch?v=bEZpY4Oe7gU',
    game: 'Street Fighter III: 3rd Strike',
  },
  {
    id: 421673,
    upload_date: '2025-12-01',
    tag: 'Fightcade FT5',
    p1_name: 'Duralath',
    p1_char: 'Alex',
    p2_name: 'dshon',
    p2_char: 'Alex',
    video_link: 'https://www.youtube.com/watch?v=6nNiT87Vdps',
    game: 'Street Fighter III: 3rd Strike',
  },
  {
    id: 421516,
    upload_date: '2025-11-30',
    tag: 'Fightcade FT5',
    p1_name: 'Arlieth',
    p1_char: 'Makoto',
    p2_name: 'C-Royd',
    p2_char: 'Dudley',
    video_link: 'https://www.youtube.com/watch?v=CjiGJgbEYkI',
    game: 'Street Fighter III: 3rd Strike',
  },
  {
    id: 421389,
    upload_date: '2025-11-29',
    tag: 'Fightcade FT3',
    p1_name: 'ennuistic',
    p1_char: 'Oro',
    p2_name: 'diabolicalcium',
    p2_char: 'Alex',
    video_link: 'https://www.youtube.com/watch?v=mI1CMrtOibQ',
    game: 'Street Fighter III: 3rd Strike',
  },
  {
    id: 421262,
    upload_date: '2025-11-28',
    tag: 'Fightcade FT5',
    p1_name: 'flexmoney',
    p1_char: 'Dudley',
    p2_name: 'RENOB',
    p2_char: 'Dudley',
    video_link: 'https://www.youtube.com/watch?v=9EErOwEipto',
    game: 'Street Fighter III: 3rd Strike',
  },
  {
    id: 421115,
    upload_date: '2025-11-27',
    tag: 'Fightcade FT5',
    p1_name: 'dshon',
    p1_char: 'Sean',
    p2_name: 'Inthul',
    p2_char: 'Q',
    video_link: 'https://www.youtube.com/watch?v=i9FP-zIcQCo',
    game: 'Street Fighter III: 3rd Strike',
  },
  {
    id: 420963,
    upload_date: '2025-11-26',
    tag: 'Fightcade FT5',
    p1_name: 'Mar',
    p1_char: 'Makoto',
    p2_name: 'Earth_Hu',
    p2_char: 'Ken',
    video_link: 'https://www.youtube.com/watch?v=EmIxaAO5VOU',
    game: 'Street Fighter III: 3rd Strike',
  },
  {
    id: 420562,
    upload_date: '2025-11-24',
    tag: 'Fightcade FT5',
    p1_name: 'koaranoma-chi',
    p1_char: 'Yun',
    p2_name: 'TAX-holyperson-',
    p2_char: 'Akuma',
    video_link: 'https://www.youtube.com/watch?v=Pv527k24NLg',
    game: 'Street Fighter III: 3rd Strike',
  },
  {
    id: 420297,
    upload_date: '2025-11-23',
    tag: 'Fightcade FT5',
    p1_name: 'Inthul',
    p1_char: 'Q',
    p2_name: 'Shorin',
    p2_char: 'Oro',
    video_link: 'https://www.youtube.com/watch?v=CGbj-Lu4Yjc',
    game: 'Street Fighter III: 3rd Strike',
  },
  {
    id: 420104,
    upload_date: '2025-11-22',
    tag: 'Fightcade FT5',
    p1_name: 'AQH',
    p1_char: 'Necro',
    p2_name: 'RC_baby',
    p2_char: 'Alex',
    video_link: 'https://www.youtube.com/watch?v=fquOVLb6qrU',
    game: 'Street Fighter III: 3rd Strike',
  },
  {
    id: 419769,
    upload_date: '2025-11-20',
    tag: 'Fightcade FT3',
    p1_name: 'flexmoney',
    p1_char: 'Dudley',
    p2_name: 'korcotxan',
    p2_char: 'Hugo',
    video_link: 'https://www.youtube.com/watch?v=Gb3ewdXb-L4',
    game: 'Street Fighter III: 3rd Strike',
  },
  {
    id: 419641,
    upload_date: '2025-11-19',
    tag: 'Fightcade FT5',
    p1_name: 'riiya',
    p1_char: 'Makoto',
    p2_name: 'Caster Mild 5',
    p2_char: 'Yang',
    video_link: 'https://www.youtube.com/watch?v=gKyRLhicXYY',
    game: 'Street Fighter III: 3rd Strike',
  },
  {
    id: 419368,
    upload_date: '2025-11-18',
    tag: 'Fightcade FT5',
    p1_name: '90000',
    p1_char: 'Ken',
    p2_name: 'okakoro',
    p2_char: 'Makoto',
    video_link: 'https://www.youtube.com/watch?v=QIxfGxody7I',
    game: 'Street Fighter III: 3rd Strike',
  },
  {
    id: 419014,
    upload_date: '2025-11-17',
    tag: 'Fightcade FT5',
    p1_name: 'Bafael',
    p1_char: 'Oro',
    p2_name: 'Nica K.O',
    p2_char: 'Akuma',
    video_link: 'https://www.youtube.com/watch?v=YLBlMRj15bA',
    game: 'Street Fighter III: 3rd Strike',
  },
  {
    id: 418568,
    upload_date: '2025-11-16',
    tag: 'Fightcade FT5',
    p1_name: 'number1gouki',
    p1_char: 'Akuma',
    p2_name: 'Chiclosos',
    p2_char: 'Urien',
    video_link: 'https://www.youtube.com/watch?v=BC4uEAkacxU',
    game: 'Street Fighter III: 3rd Strike',
  },
  {
    id: 418569,
    upload_date: '2025-11-15',
    tag: 'Fightcade FT5',
    p1_name: '812',
    p1_char: 'Ken',
    p2_name: 'diabolicalcium',
    p2_char: 'Alex',
    video_link: 'https://www.youtube.com/watch?v=hvQ0uLUfVCg',
    game: 'Street Fighter III: 3rd Strike',
  },
  {
    id: 418570,
    upload_date: '2025-11-14',
    tag: 'Fightcade FT5',
    p1_name: 'Vencabot',
    p1_char: 'Alex',
    p2_name: 'Buu HaHa',
    p2_char: 'Twelve',
    video_link: 'https://www.youtube.com/watch?v=CEMyFgim4Jc',
    game: 'Street Fighter III: 3rd Strike',
  },
  {
    id: 418571,
    upload_date: '2025-11-13',
    tag: 'Fightcade FT5',
    p1_name: 'TenRUN',
    p1_char: 'Ibuki',
    p2_name: 'Cruise',
    p2_char: 'Urien',
    video_link: 'https://www.youtube.com/watch?v=BbIc7-PMcCc',
    game: 'Street Fighter III: 3rd Strike',
  },
  {
    id: 418381,
    upload_date: '2025-11-12',
    tag: 'Fightcade FT5',
    p1_name: 'Earth_Hu',
    p1_char: 'Hugo',
    p2_name: 'Arcoilis',
    p2_char: 'Yun',
    video_link: 'https://www.youtube.com/watch?v=J7-huIG-ifM',
    game: 'Street Fighter III: 3rd Strike',
  },
  {
    id: 418181,
    upload_date: '2025-11-11',
    tag: 'Fightcade FT5',
    p1_name: 'Otana',
    p1_char: 'Ken',
    p2_name: 'TheKingOfThirdStrike',
    p2_char: 'Chun-Li',
    video_link: 'https://www.youtube.com/watch?v=bwabyNWdpho',
    game: 'Street Fighter III: 3rd Strike',
  },
  {
    id: 418051,
    upload_date: '2025-11-10',
    tag: 'Fightcade FT5',
    p1_name: 'number1gouki',
    p1_char: 'Akuma',
    p2_name: 'orogasm',
    p2_char: 'Oro',
    video_link: 'https://www.youtube.com/watch?v=mOfGpfXAwy8',
    game: 'Street Fighter III: 3rd Strike',
  },
  {
    id: 417871,
    upload_date: '2025-11-09',
    tag: 'Fightcade FT5',
    p1_name: 'SHD Artayes',
    p1_char: 'Necro',
    p2_name: 'Feetwork101',
    p2_char: 'Dudley',
    video_link: 'https://www.youtube.com/watch?v=GRsHibGPPWg',
    game: 'Street Fighter III: 3rd Strike',
  },
  {
    id: 417745,
    upload_date: '2025-11-08',
    tag: 'Fightcade FT5',
    p1_name: 'queege',
    p1_char: 'Ken',
    p2_name: 'Nica K.O',
    p2_char: 'Dudley',
    video_link: 'https://www.youtube.com/watch?v=FdhOnlG9zSg',
    game: 'Street Fighter III: 3rd Strike',
  },
  {
    id: 417555,
    upload_date: '2025-11-07',
    tag: 'Fightcade FT3',
    p1_name: 'SuperHyperBomb',
    p1_char: 'Alex',
    p2_name: 'konikonikoni',
    p2_char: 'Hugo',
    video_link: 'https://www.youtube.com/watch?v=o7hmcHrMK8g',
    game: 'Street Fighter III: 3rd Strike',
  },
  {
    id: 417390,
    upload_date: '2025-11-06',
    tag: 'Fightcade FT5',
    p1_name: 'JEWELBOX',
    p1_char: 'Elena',
    p2_name: 'ofresco2',
    p2_char: 'Ibuki',
    video_link: 'https://www.youtube.com/watch?v=JFlVWXrfIgw',
    game: 'Street Fighter III: 3rd Strike',
  },
  {
    id: 417261,
    upload_date: '2025-11-05',
    tag: 'Fightcade FT5',
    p1_name: 'Karakusa_Spammer',
    p1_char: 'Makoto',
    p2_name: 'dshon',
    p2_char: 'Sean',
    video_link: 'https://www.youtube.com/watch?v=fmWq54ewGm4',
    game: 'Street Fighter III: 3rd Strike',
  },
  {
    id: 417099,
    upload_date: '2025-11-04',
    tag: 'Fightcade FT5',
    p1_name: 'TenRUN',
    p1_char: 'Ibuki',
    p2_name: 'PattyBam',
    p2_char: 'Makoto',
    video_link: 'https://www.youtube.com/watch?v=m28qmfCgero',
    game: 'Street Fighter III: 3rd Strike',
  },
  {
    id: 416914,
    upload_date: '2025-11-03',
    tag: 'Fightcade FT3',
    p1_name: 'Inthul',
    p1_char: 'Q',
    p2_name: 'TheNerdyBA',
    p2_char: 'Makoto',
    video_link: 'https://www.youtube.com/watch?v=CmUGDt35Vas',
    game: 'Street Fighter III: 3rd Strike',
  },
  {
    id: 416733,
    upload_date: '2025-11-02',
    tag: 'Fightcade FT5',
    p1_name: 'Alexander Newhati',
    p1_char: 'Hugo',
    p2_name: 'diabolicalcium',
    p2_char: 'Alex',
    video_link: 'https://www.youtube.com/watch?v=6oKdhwZf6Gs',
    game: 'Street Fighter III: 3rd Strike',
  },
  {
    id: 416593,
    upload_date: '2025-11-01',
    tag: 'Fightcade FT5',
    p1_name: 'kmion33',
    p1_char: 'Dudley',
    p2_name: 'tkross-Itachi',
    p2_char: 'Yun',
    video_link: 'https://www.youtube.com/watch?v=X9sKSt2v73g',
    game: 'Street Fighter III: 3rd Strike',
  },
  {
    id: 416459,
    upload_date: '2025-10-31',
    tag: 'Fightcade FT5',
    p1_name: 'Sir. Weon',
    p1_char: 'Ryu',
    p2_name: '[SEBA]',
    p2_char: 'Yun',
    video_link: 'https://www.youtube.com/watch?v=IjXg6WkRlMo',
    game: 'Street Fighter III: 3rd Strike',
  },
  {
    id: 416280,
    upload_date: '2025-10-30',
    tag: 'Fightcade FT5',
    p1_name: 'XxXdankstormXL',
    p1_char: 'Yang',
    p2_name: 'dshon',
    p2_char: 'Sean',
    video_link: 'https://www.youtube.com/watch?v=HTCAwVamUP0',
    game: 'Street Fighter III: 3rd Strike',
  },
  {
    id: 416144,
    upload_date: '2025-10-29',
    tag: 'Fightcade FT5',
    p1_name: 'rokich',
    p1_char: 'Ibuki',
    p2_name: 'Otana',
    p2_char: 'Ken',
    video_link: 'https://www.youtube.com/watch?v=6bPQaVS0300',
    game: 'Street Fighter III: 3rd Strike',
  },
  {
    id: 415977,
    upload_date: '2025-10-28',
    tag: 'Fightcade FT5',
    p1_name: 'akaata1',
    p1_char: 'Yang',
    p2_name: 'Cruise',
    p2_char: 'Urien',
    video_link: 'https://www.youtube.com/watch?v=Z76IFO0dVvo',
    game: 'Street Fighter III: 3rd Strike',
  },
  {
    id: 1,
    upload_date: '2025-10-28',
    tag: 'Fightcade FT5',
    p1_name: 'akaata1',
    p1_char: 'Yang',
    p2_name: 'Cruise',
    p2_char: 'Urien',
    video_link: ' https://www.youtube.com/watch?v=N4F0RUCN_IE',
    game: 'Street Fighter III: 3rd Strike',
  },
];

// Helper function to extract video ID from YouTube URL
export function extractVideoId(url: string): string {
  const match = url.match(/[?&]v=([^&]+)/);
  return match ? match[1] : '';
}
